local especie={
	humano={
		classes={Ladrao={nivel=1};};
		raca="humano";
		statusbase={
			vida={atu=100;max=100};
			mana={atu=50;max=50};
			energia=30;
			forca=1;
			magia=1;
			velocidade=1;
			peso=75;
		};
	};
	elfo={
		classes={Arqueiro={nivel=1};};
		raca="elfo";
		statusbase={
			vida={atu=100;max=100};
			mana={atu=50;max=50};
			energia=30;
			forca=1;
			magia=1;
			velocidade=1;
			peso=65;
		};
	};
	anao={
		classes={Ferreiro={nivel=1};};
		raca="anao";
		statusbase={
			vida={atu=100;max=100};
			mana={atu=50;max=50};
			energia=30;
			forca=10;
			magia=1;
			velocidade=1;
			peso=85;
		};
	};
}

return especie